# -----------------------------------------------------------------------------
# Generic Azure CI/CD Pipeline kickstart for Powershell ModuleBuilder Modules.
#
# IMPORTANT: requires installing the Visual Studio Marketplace extension
# "Gitversion" into your Azure Devops organization. Found at:
# https://marketplace.visualstudio.com/items?itemName=gittools.gitversion
# -----------------------------------------------------------------------------

name: $(GitVersion_InformationalVersion)

trigger:
- master

pr:
- master

variables:
  ArtifactName: Modules
  enablePSGallery: true
  enableGithubReleases: true
  enableCodeCovIO: true

stages:

# -----------------------------------------------------------------------------
# Stage 1 - Continuous Integration (CI)
# -----------------------------------------------------------------------------
- stage: Build
  jobs:
  - template: .azure-templates/jobs/ci/initialize.yml
  - template: .azure-templates/jobs/ci/gitversion.yml
  - template: .azure-templates/jobs/ci/build-module.yml
    parameters:
      dependsOn: [Gitversion]
      artifactName: $(ArtifactName)

# -----------------------------------------------------------------------------
# Stage 2 - Continuous Integration (CI)
# -----------------------------------------------------------------------------
- stage: Validate
  dependsOn: Build
  jobs:
  - template: .azure-templates/jobs/ci/script-analyzer.yml
    parameters:
      dependsOn: []
      artifactName: $(ArtifactName)

  - template: .azure-templates/jobs/ci/pester.yml
    parameters:
      dependsOn: []
      artifactName: $(ArtifactName)
      TestsDirectory: '$(Build.SourcesDirectory)/Tests' # Linux users: be aware of the upperase T
      strategy:
        matrix:
          Linux:
            vmImage: 'ubuntu-latest'
          MacOS:
            vmImage: 'macOS-10.14'
          Windows:
            vmImage: 'windows-2019'
      pool:
        vmImage: $(vmImage)

# -----------------------------------------------------------------------------
# Stage 3 - Continuous Deployment (CD)
# -----------------------------------------------------------------------------
# IMPORTANT:
# - stage skipped completely if not on the master branch
# - job steps not executed if the commit message contains [no-release]
# -----------------------------------------------------------------------------
- stage: Publish
  dependsOn: Validate
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  # ---------------------------------------------------------------------------
  # Publish new module to the PSGallery
  # ---------------------------------------------------------------------------
  jobs:
  - template: .azure-templates/jobs/cd/psgallery-publish-module.yml
    parameters:
      artifactName: $(ArtifactName)

  # ---------------------------------------------------------------------------
  # Github only: commit updated manifest, then create Github Release
  # ---------------------------------------------------------------------------
  - template: .azure-templates/jobs/cd/github-create-release.yml
    parameters:
      dependsOn: ['PSGallery']
      artifactName: $(ArtifactName)
      githubName: 'alt3'
      githubRepo: 'Docusaurus.Powershell'
