# https://docs.netlify.com/configure-builds/file-based-configuration/
# https://gist.github.com/DavidWells/43884f15aed7e4dcb3a6dad06430b756

build:
  base: website/
  publish: build
  command: npm run build
  ignore: git diff --quiet HEAD^ HEAD ../website/

context:
  production:
    environment:
      NODE_ENV: 16
