name: "PSGallery Publisher"
description: "Published the new module to the PSGallery"

inputs:
  modulePath:
    description: The path to the module artifact
    required: true

runs:
  using: composite
  steps:
    - name: Download Build Output
      uses: actions/download-artifact@v2

    - name: Publish to PSGallery
      shell: pwsh
      run: ${{ github.action_path }}/action.ps1 -ModulePath ${{ inputs.modulePath }}
