name: "PSGallery Publisher"
description: "Published the new module to the PSGallery"

inputs:
  modulePath:
    description: "The path to the module artifact"
    required: true

env:
  PSGALLERY_API_KEY : ${{ secrets.PSGALLERY_API_KEY }}

runs:
  using: composite
  steps:
    - id: publish
      shell: pwsh
      run: ${{ github.action_path }}/action.ps1 -ModulePath ${{ inputs.modulePath }}
