name: "Generate Release Notes"
description: "Generates release notes in Markdown format"

runs:
  using: composite
  steps:
    - name: Checkout Master
      uses: actions/checkout@v2
      with:
        ref: master
        path: _master
        fetch-depth: 0 # fetch history for all tags and branches

    - name: Generate Release Notes
      shell: pwsh
      run: ${{ github.action_path }}/action.ps1

    - name: Upload Release Notes
      uses: actions/upload-artifact@v2
      with:
        name: Release Notes
        path: ${{github.workspace}}/_master/CHANGELOG.md
