name: Bump Module Manifest Version
description: "Replaces module manifest on master with bumped version, then commits the change to master"

inputs:
  artifactPath:
    description: Path to the artifact holding the newly built module (with bumped manifest version)
    required: true
  module:
    description: Full name of the module
    required: true    

runs:
  using: composite
  steps:
    - name: Checkout Master
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0 # fetch history for all tags and branches

    - name: Bump Module Manifest
      shell: pwsh
      run: ${{ github.action_path }}/action.ps1 -ArtifactPath ${{ inputs.artifactPath }} -Module ${{ inputs.module}}
