# -----------------------------------------------------------------------------
# Checks the Docusuaurus.Powershell production website for dead links every
# 1st day of the month and creates a Github issue (using the markdown template)
# if any are detected.
#
# Please note that we are deliberately not running this action for Pull
# Requests to prevent harassing contributors and mixing PR content.
#
# Uses:
# - https://github.com/stevenvachon/broken-link-checker
# - https://github.com/marketplace/actions/create-an-issue
# - https://crontab.guru/#0_1_1_*_*
#
# To run on your local machine:
# => npx broken-link-checker https://docusaurus-powershell.netlify.app/ --ordered --recursive
# -----------------------------------------------------------------------------

name: Broken Links Checker
on:
  schedule:
    - cron:  '0 1 1 * *'
env:
  WEBSITE_URL: "https://docusaurus-powershell.netlify.app/"
  ISSUE_TEMPLATE: ".github/workflows/check-broken-links.md"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Run Broken Links Checker
      run: npx broken-link-checker $WEBSITE_URL --ordered --recursive

    - uses: actions/checkout@v2
      if: failure()

    - uses: JasonEtco/create-an-issue@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: ${{ env.ISSUE_TEMPLATE }}
      if: failure()
